### PR TITLE
Use Polyanya for path finding

### LINKED ISSUE #168: Crash during pathfinding
```
thread 'Async Compute Task Pool (0)' panicked at 'assertion failed: left_count <= 2', crates/pathing/src/funnel.rs:78:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (2)' panicked at 'task has failed', /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.2.0/src/task.rs:425:45
thread 'main' panicked at 'task has failed', /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.2.0/src/task.rs:425:45
```

This happened when I built a Power Hub in the target direction.

### LINKED ISSUE #406: Crash during path finding
`assertion failed: Point::from(new - eye) != Point::origin()`

https://github.com/DigitalExtinction/Game/blob/3a74cb1e9602fd145cbe6d46acddaf6e37a1c404/crates/pathing/src/geometry.rs#L30

### LINKED ISSUE #407: Experiment with Polyanya based path finding
[Polyanya.pdf](https://github.com/DigitalExtinction/Game/files/10711492/Polyanya.pdf)

Modification of current path finding algorithm should be simple since the algorithm used is very similar to Polyanya. The reasons to migrate to Polyanya are twofold:

* Polyanya always finds an optimal path,
* the algorithm is peer-reviewed and well described in a paper (thus more approachable by new contributors).

Make sure that the algorithm is fast enough.

We cannot use Polyanya as is, since we need path to distance and incomplete path search as well. Simple modifications to Polyanya would work though.

### PR DESCRIPTION
**Pull request by Indy2222**
https://www.ijcai.org/proceedings/2017/0070.pdf

Fixes #407.
Fixes #406.
Fixes #168.

### CODE REVIEW

File: crates/pathing/src/finder.rs [hunk 1]
```diff
@@ -192,33 +192,48 @@ impl PathFinder {
...
-    fn locate_triangle_edges(&self, point: Point<f32>) -> Vec<u32> {
-        self.triangles
-            .locate_all_at_point(&[point.x, point.y])
-            .flat_map(|t| t.neighbours(point))
-            .collect()
+    fn locate_triangle_edges(&self, point: Point<f32>) -> Vec<Step> {
+        let mut result = Vec::new();
+        for triangle in self.triangles.locate_all_at_point(&[point.x, point.y]) {
+            for edge_id in triangle.neighbours(point) {
+                result.push(Step::new(edge_id, triangle.triangle_id()))
```
Comment (Indy2222) [inline crates/pathing/src/finder.rs:199]: This may result in edge duplication (if the point is exactly at the edge).

File: crates/pathing/src/interval.rs [hunk 2]
```diff
@@ -0,0 +1,551 @@
...
+    }
+
+    /// Apply the parameters on the parent line segment and return the
+    /// (sub-)segment.
+    fn apply(&self, segment: Segment) -> Segment {
+        debug_assert!(segment.length() > 0.);
+        let dir = segment.scaled_direction();
+        Segment::new(
+            if self.0 == 0. {
+                // To avoid rounding errors around corners.
```
Comment (Indy2222) [inline crates/pathing/src/interval.rs:324]: This should be unnecessary.
